[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10000
fs_permissions = [{ access = "read", path = "../fixtures" }]

[fuzz]
runs = 1024

[fmt]
line_length = 80
